import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./api/components/Navbar";
import MyprofilePics from "./api/components/MyprofilePics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Junsung Lee Blog",
  description: "Generated by Jongseop Lee",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <Navbar />
        <MyprofilePics />
        {children}
      </body>
    </html>
  );
}
